#!/bin/bash
echo

RED='\033[0;31m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

printf " > ${MAGENTA}Reset database..${NC}\n"
php artisan uska-internal:db:reset -v

printf " > ${MAGENTA}Migrate database..${NC}\n"
php artisan migrate -v

printf " > ${MAGENTA}Seed database..${NC}\n"
php artisan db:seed -v

printf " > ${MAGENTA}Run Unit Tests..${NC}\n"
./vendor/bin/phpunit --no-coverage --testdox

printf " > ${CYAN}Done.${NC}\n"
