#!/bin/bash
echo

RED='\033[0;31m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

printf " > ${MAGENTA}Fetch origin & upstream.${NC}\n"

git fetch origin
git fetch upstream

printf " > ${MAGENTA}Checkout and rebase development.${NC}\n"

git checkout development
git rebase upstream/development

printf " > ${MAGENTA}Delete merged branches.${NC}\n"

git branch --merged | grep -v -e "master" -e "development" | xargs git branch -D

printf " > ${MAGENTA}Prune origin & upstream.${NC}\n"

git remote prune origin
git remote prune upstream

printf " > ${CYAN}Done.${NC}\n"
