#!/usr/bin/env bash

# Git
alias gl='git log --oneline --all --graph --decorate -n 10'
alias gitcount='git shortlog -s'
alias gitworktree='function _gitworktree(){ git worktree add -b $1 $2  ; }; _gitworktree'

# Heroku
alias herokumap='heroku git:remote -a'

# Youtube
alias youtube-pl='youtube-dl --ignore-errors --extract-audio --audio-format mp3 --download-archive archive.txt'
alias youtube-txt='function _youtubeTxt(){ cat $1 | while read line ; do youtube-dl -x --audio-format=mp3 --audio-quality=0 $line ; done; }; _youtubeTxt'
alias youtube-mp3='youtube-dl --ignore-errors -x --audio-quality 0 --audio-format best'

# Zip
alias tarz='tar -czvf'
alias tarx='tar -xzvf'

# Sys
alias duh='du -h -d 1 | sort -h'

alias encryptCompress='function _encryptCompress(){ tar -czf - $1 | openssl enc -aes-256-cbc -e > $2 ; }; _encryptCompress'
alias decryptCompress='function _decryptCompress(){ openssl enc -aes-256-cbc -d -in $1 | tar xz ; }; _decryptCompress'

alias vid2fullhd='function _vid2fullhd(){ ffmpeg -i $1 -s 1080x1920 -acodec copy ${1%.*}-fhd.mp4  ; }; _vid2fullhd'
alias vidMovToMp4='function _vidMovToMp4(){ ffmpeg -i $1 -vcodec h264 -acodec aac ${1%.*}.mp4 ; }; _vidMovToMp4'
alias vidScaleTo='function _vidScaleTo(){ ffmpeg -i $1 -vf scale="$2:-1" ${1%.*}-$2w.mp4 ; }; _vidScaleTo'
alias vidCleanFrames='function _vidCleanFrames(){ ffmpeg -i $1 -vf mpdecimate -vsync vfr ${1%.*}-clean.mp4  ; }; _vidCleanFrames'
alias vidTemp='ffmpeg -f lavfi -i testsrc -t 30 -pix_fmt yuv420p vidTemp.mp4'

alias bashbible='open https://github.com/dylanaraps/pure-bash-bible'

# Java
alias jarList='jar tvf'

# Java versions
alias j19="export JAVA_HOME=`/usr/libexec/java_home -v 19 -a arm64`; java -version"
alias j18="export JAVA_HOME=`/usr/libexec/java_home -v 18 -a arm64`; java -version"
#alias j11="export JAVA_HOME=`/usr/libexec/java_home -v 11`; java -version"
alias j8i="export JAVA_HOME='/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home'; java -version"
alias j8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8 -a arm64`; java -version"
