#!/usr/bin/env bash

# Git
alias gl='git log --oneline --all --graph --decorate -n 10'
alias gitcount='git shortlog -s'

# Heroku
alias herokumap='heroku git:remote -a'

# Youtube
alias youtube-pl='youtube-dl --ignore-errors --extract-audio --audio-format mp3 --download-archive archive.txt'
alias youtube-txt='function _youtubeTxt(){ cat $1 | while read line ; do youtube-dl -x --audio-format=mp3 --audio-quality=0 $line ; done; }; _youtubeTxt'
alias youtube-mp3='youtube-dl --ignore-errors -x --audio-quality 0 --audio-format best'

# Zip
alias tarz='tar -czvf'
alias tarx='tar -xzvf'

# Sys
alias duh='du -h -d 1 | sort -h'

alias encryptCompress='function _encryptCompress(){ tar -czf - $1 | openssl enc -aes-256-cbc -e > $2 ; }; _encryptCompress'
alias decryptCompress='function _decryptCompress(){ openssl enc -aes-256-cbc -d -in $1 | tar xz ; }; _decryptCompress'

alias vid2fullhd='function _vid2fullhd(){ ffmpeg -i $1 -s 1080x1920 -acodec copy $1-fhd.mp4  ; }; _vid2fullhd'

alias bashbible='open https://github.com/dylanaraps/pure-bash-bible'

# Java
alias jarList='jar tvf'

# Java versions
# alias j13="export JAVA_HOME=`/usr/libexec/java_home -v 13`; java -version"
alias j12="export JAVA_HOME=`/usr/libexec/java_home -v 12`; java -version"
alias j11="export JAVA_HOME=`/usr/libexec/java_home -v 11`; java -version"
#alias j10="export JAVA_HOME=`/usr/libexec/java_home -v 10`; java -version"
#alias j9="export JAVA_HOME=`/usr/libexec/java_home -v 9`; java -version"
alias j8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; java -version"
#alias j7="export JAVA_HOME=`/usr/libexec/java_home -v 1.7`; java -version"
