#!/bin/bash

RED='\033[0;31m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

if [ "$1" == "" ] || [ "$2" == "" ]; then
    printf "${MAGENTA}Requires two arguments.${NC}\n"
    exit
fi

# https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality
# ffmpeg -y -ss 30 -t 3 -i input.flv -vf fps=10,scale=320:-1:flags=lanczos,palettegen palette.png
# ffmpeg -ss 30 -t 3 -i input.flv -i palette.png -filter_complex "fps=10,scale=320:-1:flags=lanczos[x];[x][1:v]paletteuse" output.gif

ffmpeg -y -i $1 -vf fps=24,scale=320:-1:flags=lanczos,palettegen palette.png
ffmpeg $1 -i palette.png -filter_complex "fps=24,scale=320:-1:flags=lanczos[x];[x][1:v]paletteuse" $2
